### ISSUE TITLE
В чем задумка с серыми блоками

### ISSUE THREAD

**Issue by nchudnovets** [puzankov/markup_online#2]
Есть ли какой то контакт с дизайнером заказчика? Не совсем понимаю, в чем его задумка.
В разделе The Undiscovered Beauty три блока с фотографиями. Две фоторграфии помещены в блоки-подложки с серым бэкграундом, а третья в блок с белым. При этом, на этой третьей в макете прорисован ховер.

Если макет увеличить и посмотреть внимательно на первые два серых блока, то видно, что они, хоть и похожи, но оттенок у них немного разный (первый темнее, второй светлее), цвет бордера внизу тоже немного разный (первый темнее, второй светлее).

Теперь вопрос. По задумке дизайнера это три блока со статичными цветами подложки под фото (первый серый темнее, второй серый светлее, третий белый) ? Или, все же, это три серых блока подолжки, которые по ховеру становятся белыми?

Исходя из того, что в третьем блоке не прорисовано второе состояние, то я прихожу к выводу, что это три блока со статичными цветами.
Но хотелось бы иметь комментарий дизайнера, что он имелл ввиду, если это возможно, Или комментарий заказчика, как ему надо.

**Comment by puzankov** [comment]
Комментарий от дизайнера:

Белое состояние - это hover state на всем блоке
Левый и средний блоки можно сделать одинакового цвета, выбери какой больше нравится.
