### ISSUE TITLE
Ховер в подменю

### ISSUE THREAD

**Issue by serhiitolstoi** [puzankov/markup_online#3]
В пункте подменю "Articles" видим фон и мелкий текст под ним. 
Фон и/или текст должны появлятся по наведению мыши или оно статично в каждом первом пункте подменю?

**Comment by puzankov** [comment]
появляться должен только фон

**Comment by gorbatyuks** [comment]
але там ще є прихований жовтий фон знизу, він коли має появлятися?

**Comment by puzankov** [comment]
Разрешаю сделать ее по желанию - хотите добавьте эту полоску по ховеру.
Хотите не добавляйте
