### ISSUE TITLE
exam: скрытые слои в блоке с пауком

### ISSUE THREAD

**Issue by nchudnovets** [puzankov/markup_online#4]
В блоке с пауком , среди слоев Present button, есть два скрытых по умолчанию слоя.
Один с текстом "or just click here and find out more", второй с какой-то кракозяблинкой, называется 1335036455_gift.
В каких случаях они должны появляться, должны ли вообще?
Или они случайно скрыты, а на самом деле должны присутствовать постоянно?

**Comment by puzankov** [comment]
Их не должно быть вообще
удалил их из исходника
спасибо
